### ISSUE TITLE
Error when SSL enabled in CouchPotato

### ISSUE THREAD

**Issue by jmseaton** [josephschmitt/alexa-couchpotato#29]
I have this working with my setup, but not so well when I enable SSL.  I have a cert from RapidSSL, and it shows valid in Chrome, so I know it's not an issue with certificate validity.  I have also made the changes in the config.json, and uploaded the zip to the Lambda function.

I'm getting the following response when I enable SSL on CouchPotato:
```
"outputSpeech": {
      "type": "SSML",
      "ssml": "<speak>An error occured: Error: read ECONNRESET</speak>"
    }

```
In the CouchPotato logs:
```
06-08 18:32:01 ERROR Uncaught exception
Traceback (most recent call last):
  File "/apps/couchpotato/libs/tornado/http1connection.py", line 691, in _server_request_loop
    ret = yield conn.read_response(request_delegate)
  File "/apps/couchpotato/libs/tornado/gen.py", line 807, in run
    value = future.result()
  File "/apps/couchpotato/libs/tornado/concurrent.py", line 209, in result
    raise_exc_info(self._exc_info)
  File "/apps/couchpotato/libs/tornado/gen.py", line 810, in run
    yielded = self.gen.throw(*sys.exc_info())
  File "/apps/couchpotato/libs/tornado/http1connection.py", line 166, in _read_message
    quiet_exceptions=iostream.StreamClosedError)
  File "/apps/couchpotato/libs/tornado/gen.py", line 807, in run
    value = future.result()
  File "/apps/couchpotato/libs/tornado/concurrent.py", line 209, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
SSLError: [SSL: HTTP_REQUEST] http request (_ssl.c:581)
```

**Comment by jmseaton** [comment]
Figured it out.

Needed to add "ssl":"true" to the config/default.json

**Comment by jmseaton** [comment]
Okay, sorry for closing and re-opening.  Adding "ssl":"true" to config/default.json fixed my connection. 
Though seems like it uncovered another one with SSL and CouchPotato.
